CREATE TABLE IF NOT EXISTS User (
userId INT AUTO_INCREMENT PRIMARY KEY,
firstName VARCHAR(50) NOT NULL,
lastName VARCHAR(50) NOT NULL,
password VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE

);

CREATE TABLE IF NOT EXISTS Orders (
orderId INT AUTO_INCREMENT PRIMARY KEY,
OrderDate   Date NOT NULL;
TotalAmount VARCHAR(30) NOT NULL;
OrderStatus VARCHAR(30) NOT NULL;
CONSTRAINT userFK FOREIGN KEY(userId) REFERENCES User(userId)  
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    ProductId INT AUTO_INCREMENT PRIMARY KEY,
    ProductName VARCHAR(255) NOT NULL,
    ProductDescription TEXT,
    Price DECIMAL(10, 2) NOT NULL,
    StockQuantity INT NOT NULL,
    Img VARCHAR(255),
    CategoryId INT,
    CONSTRAINT categoryFK FOREIGN KEY (CategoryId) REFERENCES CATEGORY(CategoryId)
);
